# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Border_Calibration.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Border_Calibration(object):
    def setupUi(self, Border_Calibration):
        Border_Calibration.setObjectName("Border_Calibration")
        Border_Calibration.resize(904, 539)
        self.centralwidget = QtWidgets.QWidget(Border_Calibration)
        self.centralwidget.setObjectName("centralwidget")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(700, 460, 91, 31))
        self.ok_button.setObjectName("ok_button")
        self.slider0x = QtWidgets.QSlider(self.centralwidget)
        self.slider0x.setGeometry(QtCore.QRect(110, 350, 160, 28))
        self.slider0x.setOrientation(QtCore.Qt.Horizontal)
        self.slider0x.setObjectName("slider0x")
        self.slider0y = QtWidgets.QSlider(self.centralwidget)
        self.slider0y.setGeometry(QtCore.QRect(110, 380, 160, 28))
        self.slider0y.setOrientation(QtCore.Qt.Horizontal)
        self.slider0y.setObjectName("slider0y")
        self.slider1x = QtWidgets.QSlider(self.centralwidget)
        self.slider1x.setGeometry(QtCore.QRect(380, 350, 160, 28))
        self.slider1x.setOrientation(QtCore.Qt.Horizontal)
        self.slider1x.setObjectName("slider1x")
        self.slider1y = QtWidgets.QSlider(self.centralwidget)
        self.slider1y.setGeometry(QtCore.QRect(380, 380, 160, 28))
        self.slider1y.setOrientation(QtCore.Qt.Horizontal)
        self.slider1y.setObjectName("slider1y")
        self.slider3y = QtWidgets.QSlider(self.centralwidget)
        self.slider3y.setGeometry(QtCore.QRect(110, 460, 160, 28))
        self.slider3y.setOrientation(QtCore.Qt.Horizontal)
        self.slider3y.setObjectName("slider3y")
        self.slider3x = QtWidgets.QSlider(self.centralwidget)
        self.slider3x.setGeometry(QtCore.QRect(110, 430, 160, 28))
        self.slider3x.setOrientation(QtCore.Qt.Horizontal)
        self.slider3x.setObjectName("slider3x")
        self.slider2y = QtWidgets.QSlider(self.centralwidget)
        self.slider2y.setGeometry(QtCore.QRect(380, 460, 160, 28))
        self.slider2y.setOrientation(QtCore.Qt.Horizontal)
        self.slider2y.setObjectName("slider2y")
        self.slider2x = QtWidgets.QSlider(self.centralwidget)
        self.slider2x.setGeometry(QtCore.QRect(380, 430, 160, 28))
        self.slider2x.setOrientation(QtCore.Qt.Horizontal)
        self.slider2x.setObjectName("slider2x")
        self.frame_img = QtWidgets.QLabel(self.centralwidget)
        self.frame_img.setGeometry(QtCore.QRect(20, 30, 427, 240))
        self.frame_img.setObjectName("frame_img")
        self.t_frame_img = QtWidgets.QLabel(self.centralwidget)
        self.t_frame_img.setGeometry(QtCore.QRect(460, 30, 427, 240))
        self.t_frame_img.setObjectName("t_frame_img")
        self.ger = QtWidgets.QLabel(self.centralwidget)
        self.ger.setGeometry(QtCore.QRect(610, 320, 251, 121))
        self.ger.setMinimumSize(QtCore.QSize(211, 81))
        self.ger.setObjectName("ger")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 350, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 380, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 350, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 380, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 430, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 460, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 430, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 460, 67, 17))
        self.label_8.setObjectName("label_8")
        Border_Calibration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Border_Calibration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 22))
        self.menubar.setObjectName("menubar")
        Border_Calibration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Border_Calibration)
        self.statusbar.setObjectName("statusbar")
        Border_Calibration.setStatusBar(self.statusbar)

        self.retranslateUi(Border_Calibration)
        QtCore.QMetaObject.connectSlotsByName(Border_Calibration)

    def retranslateUi(self, Border_Calibration):
        _translate = QtCore.QCoreApplication.translate
        Border_Calibration.setWindowTitle(_translate("Border_Calibration", "MainWindow"))
        self.ok_button.setText(_translate("Border_Calibration", "Ok"))
        self.frame_img.setText(_translate("Border_Calibration", "TextLabel"))
        self.t_frame_img.setText(_translate("Border_Calibration", "TextLabel"))
        self.ger.setText(_translate("Border_Calibration", "TextLabel"))
        self.label.setText(_translate("Border_Calibration", "x_red"))
        self.label_2.setText(_translate("Border_Calibration", "y_red"))
        self.label_3.setText(_translate("Border_Calibration", "x_green"))
        self.label_4.setText(_translate("Border_Calibration", "y_green"))
        self.label_5.setText(_translate("Border_Calibration", "x_blue"))
        self.label_6.setText(_translate("Border_Calibration", "y_blue"))
        self.label_7.setText(_translate("Border_Calibration", "x_white"))
        self.label_8.setText(_translate("Border_Calibration", "y_white"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Border_Calibration = QtWidgets.QMainWindow()
    ui = Ui_Border_Calibration()
    ui.setupUi(Border_Calibration)
    Border_Calibration.show()
    sys.exit(app.exec_())

